### ISSUE TITLE
Breaks with Webpack-3.1.0

### ISSUE THREAD

**Issue by swernerx** [60frames/webpack-hot-server-middleware#31]
I am not sure why this happens, but in my otherwise unchanged setup, updating to Webpack-3.1.0 breaks this package.

```
[00:08:58] Error: Expected webpack compiler to contain both a 'client' and 'server' config
    at webpackHotServerMiddleware (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/webpack-hot-server-middleware/src/index.js:88:15)
    at addDevMiddleware (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/edge-builder/src/express/dev.js:42:14)
    at Gulp.startDevServer (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/edge-builder/lib/node.commonjs.js:600:3)
    at module.exports (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/orchestrator/index.js:134:8)
    at /Users/sebastian/Workspace/sebastian-software/edge-boilerplate/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Webpack is triggered by Gulp as you can see.

This here is the initialization code:

```js
  const clientConfig = configBuilder({
    target: "client",
    env: "development"
  })

  const serverConfig = configBuilder({
    target: "server",
    env: "development"
  })

  const multiCompiler = webpack([ clientConfig, serverConfig ])
  const clientCompiler = multiCompiler.compilers[0]

  server.use(webpackDevMiddleware(multiCompiler, {
    // required
    publicPath: PUBLIC_PATH,

    // display no info to console (only warnings and errors)
    noInfo: true
  }))

  server.use(webpackHotMiddleware(clientCompiler))

  // keeps serverRender updated with arg: { clientStats, outputPath }
  server.use(webpackHotServerMiddleware(multiCompiler, {
    serverRendererOptions: {
      outputPath: CLIENT_OUTPUT
    }
  }))
```

Do you have any idea for a fix?

**Comment by swernerx** [comment]
That issue is probably related to this new feature: "Support array of functions as configuration" reported in the changelog.

**Comment by sokra** [comment]
cc @AndersDJohnson

**Comment by swernerx** [comment]
Sorry it seems like the issue was related to the local installation. NPM 5.x seems to be still quite fragile.

See: https://github.com/webpack/webpack/issues/5227#issuecomment-313630933
