### ISSUE TITLE
Bundle is returning empty object

### ISSUE THREAD

**Issue by Industrial** [60frames/webpack-hot-server-middleware#67]
Hi. I needed this [PR](https://github.com/60frames/webpack-hot-server-middleware/pull/64) to be able to run my new setup: Babel7 (+ TypeScript), Webpack4, React + Redux, SSR and HMR (universal). It's at [https://github.com/Industrial/universal-demo](https://github.com/Industrial/universal-demo)

Could you please try `git clone https://github.com/Industrial/universal-demo; cd universal-demo; npm i; npm run start;` and then open `http://localhost:3000` ?

I am getting the error

```
Error: The 'server' compiler must export a function in the form of `(options) => (req, res, next) => void`
    at getServerRenderer (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/webpack-hot-server-middleware/src/index.js:68:15)
    at doneHandler (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/webpack-hot-server-middleware/src/index.js:159:30)
    at SyncHook.eval (eval at create (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:9:1)
    at SyncHook.lazyCompileHook [as _call] (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/tapable/lib/Hook.js:35:21)
    at MultiCompiler.compiler.hooks.done.tap.stats (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/webpack/lib/MultiCompiler.js:45:22)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._done (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/webpack/lib/Watching.js:99:28)
    at compiler.emitRecords.err (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/webpack/lib/Watching.js:73:19)
    at Compiler.emitRecords (/home/tom/Code/Code9/JavaScript/Projects/universal-demo/node_modules/webpack/lib/Compiler.js:295:39)
```

I don't know what I'm doing wrong anymore :-(

**Comment by Industrial** [comment]
```
$ node
> x=require('./dist/server.js')
{}
>
```

**Comment by richardscarrott** [comment]
@Industrial You're missing `libraryTarget` in your webpack server config https://github.com/60frames/webpack-hot-server-middleware/blob/master/example/webpack.config.js#L24

**Comment by Industrial** [comment]
Right, got it, thanks!
